### PR TITLE
Update for Tinkoff

### PR DESCRIPTION
**Pull request by rakleed**
To filter the site journal.tinkoff.ru.

### CODE REVIEW

**Comment by Chinaski1** [comment]
`journal.tinkoff.ru `is already added to exclusions because `tinkoff.ru` domain is in the list.

**Comment by slavaleleka** [comment]
I suppose that **rakleed** wants it to be filtered, not excluded

**Comment by Chinaski1** [comment]
Replacing the wildcard with the `www.` is not a good idea, because there is a chance to snag several subdomains with sensitive information.
So the best solution would be to remove/add the desired domain locally.

**Comment by rakleed** [comment]
@Chinaski1 but you still use `www.`, here are examples:
- https://github.com/AdguardTeam/HttpsExclusions/blob/master/exclusions/android.txt#L200
- https://github.com/AdguardTeam/HttpsExclusions/blob/master/exclusions/banks.txt#L3523-L3536
- https://github.com/AdguardTeam/HttpsExclusions/blob/master/exclusions/mac.txt#L13-L18

Why not do the same in this case, since then the `journal.tinkoff.ru` domain would normally be filtered. After all, this domain has more and more announces and there is even advertising. Also, most likely there are trackers.

Isn't that more important than the very low probability of filtering a domain with sensitive information?

**Comment by rakleed** [comment]
@Chinaski1 ping

**Comment by Chinaski1** [comment]
There are certain reasons for this. For example, in the first case, only the domain for a single application is excluded.

Simply add the desired domain to the exceptions manually.

**Pull request closed without merging**
